output-dir: docs

# website settings
website:
  title: "Alzheimer’s Disease and Microbiome Atlas (ADMA)"

  #image: img/my_image.jpg
  #favicon: img/favicon.png
  
  # Navigation bar at the top of the website
  navbar:
    pinned: true
    #logo: /img/logo.png
    
    left:
      - text: "Home"
        href: Home/index.qmd
      - text: "About"
        href: About/index.qmd
      - text: "Datasets"
        href: Datasets/index.qmd
    
    # social media
    right:
      - icon: github
    #     href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
    #   - icon: twitter
    #     href: https://twitter.com/MarvinSchmittML
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
    #   - icon: envelope
    #     aria-label: email
    #     href: "mailto:mail.marvinschmitt@gmail.com"  
  

  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 CINEMA Research Group</span>
    center: |
      <span class="faux-block"><a href="https://cwru-cinema.com/">Contact CINEMA Research Group</a></span>
    # right: |
    #   <span class="faux-block"><a href="https://cwru-cinema.com/">Contact CINEMA Research Group</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true